class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.87.tar.gz"
  sha256 "8b71b4376ee261e038ef1e46133270253e49f70ea2cf9f98da05328ded9114c2"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "cc41c6d3cfbb746bca636ef3e478c05a87c6c379fe1b1f16330abd92fd96ab9c"
    sha256 cellar: :any_skip_relocation, arm64_tahoe:       "cc41c6d3cfbb746bca636ef3e478c05a87c6c379fe1b1f16330abd92fd96ab9c"
    sha256 cellar: :any_skip_relocation, arm64_sequoia:     "cc41c6d3cfbb746bca636ef3e478c05a87c6c379fe1b1f16330abd92fd96ab9c"
    sha256 cellar: :any_skip_relocation, arm64_linux:       "e34c73ab286c46cc5218ecceaf9aa8b807c8444045c18b909759c786c69520be"
    sha256 cellar: :any,                 x86_64_linux:      "ef1b0817118fcf4fcbaa52d87cff403374f8082f2021374f03d03f6c6c451e09"
  end

  depends_on "go" => :build

  deny_network_access!

  def fetch
    system "go", "mod", "download"
  end

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
