class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.5.92.tar.gz"
  sha256 "963d982dc15b7d7e9bed4dea525b84c4f2af8f74278264316f417840b32f9d4d"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "3ab2d9e2855c415b0dc8ba69f325b815dcda1609f393e7cd53a052bec2e0485e"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "3ab2d9e2855c415b0dc8ba69f325b815dcda1609f393e7cd53a052bec2e0485e"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "3ab2d9e2855c415b0dc8ba69f325b815dcda1609f393e7cd53a052bec2e0485e"
    sha256 cellar: :any_skip_relocation, sonoma:        "0a25e957c7085da94da1855e978e95fe31c674700c4da2d99eba7fe0b4e02806"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "f6549a9ec308e3646f1b9ab9852aebe52fdd62e5a8f3093c06a2723c61211c62"
    sha256 cellar: :any,                 x86_64_linux:  "4ac569de653a325f424b70e491aa3d00145a9b3835e6d4618b26ff72022f47ce"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
