class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.3.37.tar.gz"
  sha256 "da8e7e0667bda640a09f32fc532bc40e1f5a2416b3faa51948775b330f040aff"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "ea59935a963cd7ff828f421b815251632e62316a26176316d56211ab326dbd59"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "ea59935a963cd7ff828f421b815251632e62316a26176316d56211ab326dbd59"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "ea59935a963cd7ff828f421b815251632e62316a26176316d56211ab326dbd59"
    sha256 cellar: :any_skip_relocation, sonoma:        "e3618269c2aae90da84fd5cca97674500e731bea9756eb0e263938e5caf3af65"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "e95a76ece6e2617f0f8fdda9bdc86ed7cfec09896ba7a473b3bef438861e2e28"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "f2a70eee4e71074df93f68f2d2fae9bd1d3dbee2ab905322016a3edd1345195f"
  end

  # Unpin Go when Keploy supports Go 1.26
  # (when go.mod references vitess > v23.0.2, ref https://github.com/vitessio/vitess/pull/19367)
  depends_on "go@1.25" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    output = shell_output("#{bin}/keploy templatize --path #{testpath}")
    assert_match "No test sets found to templatize", output

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
