class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.12.0.tar.gz"
  sha256 "17c768f651d4e09e83a25b781a74924694838f222a1f3676c4450073161c859a"
  license any_of: ["Apache-2.0", "MIT"]
  compatibility_version 1
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "dd9a36c98da067d79ded821bf7dee9ea64a69c5411a369ee2750bf80f5076065"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "7a4bc57e9defb3bea41031a3b9b67e4111ed80bed0793171707c8d08d96d7fad"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "6047e6715bffd5390638ce22a728a4975ece8f61ce125c02c3e59855945d896a"
    sha256 cellar: :any_skip_relocation, sonoma:        "30fe26905968ffe7a421f1d300604f8df5b9bd1345812121279a6ac79625b0c3"
    sha256 cellar: :any,                 arm64_linux:   "1ee9d2959e6373feef60c0175e97eb0c3b0742d8009a22241243167fdfcb470f"
    sha256 cellar: :any,                 x86_64_linux:  "1b9e2caa33f9b8ea015697adab72bda2aa5ce23a51344e2d11552dccef4ef8b4"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
