class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.9.24.tar.gz"
  sha256 "0be6aac68cca2eba39e9b903fffe30034acb19c7d601c5fbd305edc4f4fb4dbe"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "05d8e8fe9e589d76265d48dbcd8f0ce80d81c765476bf8ab8fa08be611e841de"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "f8164cc8bcfa79851d19616f6c5e956ec3c7fe940850a489a7d38a9fbc41a0ba"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "1ebdf34a21871651151987935556a1d3f8c9bbac1db402342cdaf2165098c565"
    sha256 cellar: :any_skip_relocation, sonoma:        "c250dd08d12619db9c0b2e377999bcc85a93c7db88cd58757421cf5039c7f586"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "97d9833760397c61f186b4bac16ba49fc56979464b517eb4dc5c56953d9ab528"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "c33d05c254fd86479e7070a5358467cf6f01cbccab486cde30445942cef46246"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
