class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.12.14.tar.gz"
  sha256 "cf886aac4e27257bfb8863694a377fa3781f179e84b1eee55038b0a0f83ab7a9"
  license any_of: ["Apache-2.0", "MIT"]
  compatibility_version 1
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "8a6205bc4301973213dd205ec73d17d8ee627fbfd747bacdb0e6361a65a6a43f"
    sha256 cellar: :any_skip_relocation, arm64_tahoe:       "dae9c42c4838eac60a5f2e3938f83b06214dbec50d8670bf4679717a38e48cdc"
    sha256 cellar: :any_skip_relocation, arm64_sequoia:     "a0ab934965c381ccdd07024d80494e0429304a082dae48bc4045a207a405cbf0"
    sha256 cellar: :any,                 arm64_linux:       "0f0f05cc7a8fd872d243d594a86f6ac425ba74799eb1b8c6d793a8a7038438c0"
    sha256 cellar: :any,                 x86_64_linux:      "b7d3939e4a3e4f14446d90f8ad244fb122b5993f4bfd782c549902404ce241f1"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  on_linux do
    depends_on "jemalloc"
  end

  # downloads wheels in test
  allow_network_access! :test

  def fetch
    system "cargo", "fetch", "--locked", "--target", "host-tuple"
  end

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
